// File generated by FlutterFire CLI.// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_membersimport 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.////// Example:/// ```dart/// import 'firebase_options.dart';/// // .../// await Firebase.initializeApp(///   options: DefaultFirebaseOptions.currentPlatform,/// );/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9gC6ma3gLalAk-88VRoxzETz8zo46fVY',
    appId: '1:234096080606:web:db6378ae5f9dbc107b744f',
    messagingSenderId: '234096080606',
    projectId: 'proyecto1-74f04',
    authDomain: 'proyecto1-74f04.firebaseapp.com',
    databaseURL: 'https://proyecto1-74f04-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto1-74f04.appspot.com',
    measurementId: 'G-Q6YKW0V6H6',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5WjEFsOIpZ4m7_tVgU0TMgEowkGBh3hA',
    appId: '1:234096080606:android:4901e6df146babad7b744f',
    messagingSenderId: '234096080606',
    projectId: 'proyecto1-74f04',
    databaseURL: 'https://proyecto1-74f04-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto1-74f04.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8b8UEIJ0mSpRpKMi_nAR_PXWczcwq4pg',
    appId: '1:234096080606:ios:6f9b2b183543bf677b744f',
    messagingSenderId: '234096080606',
    projectId: 'proyecto1-74f04',
    databaseURL: 'https://proyecto1-74f04-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto1-74f04.appspot.com',
    iosClientId:
        '234096080606-5mcuktvnqj1ki6sd2tt68v86fmi85hcn.apps.googleusercontent.com',
    iosBundleId: 'co.ucundinamarca.proyecto1',
  );
}
